-- 코드를 입력하세요
SELECT u.USER_ID, u.NICKNAME, SUM(b.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS b, USED_GOODS_USER AS u
WHERE b.WRITER_ID = u.USER_ID AND b.STATUS = "DONE"
GROUP BY b.WRITER_ID
HAVING SUM(b.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC