-- 코드를 작성해주세요
SELECT 
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    MAX_SIZE - E.SIZE_OF_COLONY AS YEAR_DEV,
    E.ID
FROM
    ECOLI_DATA AS E,
    (SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
     FROM
        ECOLI_DATA
     GROUP BY
        YEAR
    ) AS E2
WHERE
    YEAR(E.DIFFERENTIATION_DATE) = E2.YEAR
ORDER BY
    YEAR, YEAR_DEV